schema_version = "1.0.0"

id = "Color_Picker_Pro"
version = "1.0.6"
name = "Color Picker Pro"
tagline = "Simple picker color in Blender"
maintainer = "AIGODLIKE Community, Cupcko <649730016@qq.com>, 小萌新"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/AIGODLIKE/Color_Picker_Pro"

# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Render", "Material", "Paint"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later", ]

copyright = [
    "2002-2024 Cupcko",
    "2022 AIGODLIKE Community",
]

wheels = [
    "./wheels/imgui_bundle-1.6.3-cp311-cp311-win_amd64.whl",
    "./wheels/typing_extensions-4.13.2-py3-none-any.whl",
    "./wheels/pydantic_core-2.33.2-cp311-cp311-win_amd64.whl",
    "./wheels/pydantic-2.11.4-py3-none-any.whl",
    "./wheels/munch-4.0.0-py2.py3-none-any.whl",
    "./wheels/typing_inspection-0.4.1-py3-none-any.whl",
]