schema_version = "1.0.0"

id = "Color_Picker"
version = "1.0.4"
name = "Color Picker"
tagline = "Simple picker color in Blender"
maintainer = "AIGODLIKE Community, Cupcko <649730016@qq.com>, 小萌新"
type = "add-on"

website = "https://github.com/AIGODLIKE/Color_Picker"

tags = ["Render", "Material", "Paint"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later", ]

copyright = [
    "2002-2024 Cupcko",
    "2022 AIGODLIKE Community",
]

wheels = [
#    "./wheels/imgui-2.0.0-cp311-cp311-win_amd64.whl",
    "./wheels/slimgui-0.3.0-cp311-cp311-win_amd64.whl",
]