schema_version = "1.0.0"

id = "Color_Picker"
version = "1.0.4"
name = "Color Picker"
tagline = "Simple picker color in Blender"
maintainer = "AIGODLIKE Community, Cupcko <649730016@qq.com>, 小萌新"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)
permissions = ["files", "network"]

# Optional link to documentation, support, source files, etc
website = "https://github.com/AIGODLIKE/Color_Picker"

# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Render", "Material", "Paint"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later", ]

copyright = [
    "2002-2024 Cupcko",
    "2022 AIGODLIKE Community",
]

wheels = [
    "./wheels/imgui-2.0.0-cp311-cp311-win_amd64.whl",
]